version: "3.9"

services:

  web:
    image: phpminds/mastermind-web:0.2
    links:
      - server
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=mastermind.phpminds.org
      - NGINX_PORT=80

  server:
    image: phpminds/mastermind-server:0.4
    ports:
      - "8085:8085"
    command: php /var/www/html/src/Server.php